lowercaseOutputName: true
lowercaseOutputLabelNames: true

rules:
  # Kafka Streams stream-level metrics
  - pattern: 'kafka.streams<type=stream-metrics, client-id=(.+)><>(.+):'
    name: kafka_streams_$2
    labels:
      client_id: "$1"
    type: GAUGE

  # Kafka Streams thread-level metrics
  - pattern: 'kafka.streams<type=stream-thread-metrics, thread-id=(.+)><>(.+):'
    name: kafka_streams_thread_$2
    labels:
      thread_id: "$1"
    type: GAUGE

  # Kafka Streams task-level metrics
  - pattern: 'kafka.streams<type=stream-task-metrics, thread-id=(.+), task-id=(.+)><>(.+):'
    name: kafka_streams_task_$3
    labels:
      thread_id: "$1"
      task_id: "$2"
    type: GAUGE

  # Kafka Streams processor-node-level metrics
  - pattern: 'kafka.streams<type=stream-processor-node-metrics, thread-id=(.+), task-id=(.+), processor-node-id=(.+)><>(.+):'
    name: kafka_streams_processor_$4
    labels:
      thread_id: "$1"
      task_id: "$2"
      processor_node_id: "$3"
    type: GAUGE

  # Kafka Consumer metrics
  - pattern: 'kafka.consumer<type=consumer-fetch-manager-metrics, client-id=(.+), topic=(.+), partition=(.+)><>(.+):'
    name: kafka_consumer_$4
    labels:
      client_id: "$1"
      topic: "$2"
      partition: "$3"
    type: GAUGE

  - pattern: 'kafka.consumer<type=consumer-fetch-manager-metrics, client-id=(.+)><>(.+):'
    name: kafka_consumer_$2
    labels:
      client_id: "$1"
    type: GAUGE

  # Kafka Producer metrics
  - pattern: 'kafka.producer<type=producer-metrics, client-id=(.+)><>(.+):'
    name: kafka_producer_$2
    labels:
      client_id: "$1"
    type: GAUGE

  - pattern: 'kafka.producer<type=producer-topic-metrics, client-id=(.+), topic=(.+)><>(.+):'
    name: kafka_producer_topic_$3
    labels:
      client_id: "$1"
      topic: "$2"
    type: GAUGE
